version: "3.8"
services:
  db:
    image: postgres:15.2
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    stdin_open: true
    tty: true
    ports:
    - 5432:5432/tcp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
  insertion_serialization_anomaly:
    build: ./
    depends_on:
      db:
        condition: service_healthy