version: "3.8"
services:
  db:
    container_name: db
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: "sql"
      MYSQL_USER: "user"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 5
  value_of_serializability:
    build: ./
    depends_on:
      db:
        condition: service_healthy